name: ff_speaker_cards
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  vector_graphics: ^1.1.11+1
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  vector_graphics_compiler: ^1.1.11+1
  scale_photo_transformer:
    path: ./scale_photo_transformer

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - path: assets/logos/
    - path: assets/photos/
      transformers:
        - package: scale_photo_transformer
    - path: assets/svgs/
      transformers:
        - package: vector_graphics_compiler
  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura.ttc