name: scale_photo_transformer
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  image: ^4.2.0

dev_dependencies:
  lints: ^4.0.0
